from pathlib import Path
import json,re,html,xml.etree.ElementTree as ET,collections
import os
ROOT=Path(__file__).resolve().parents[1]
REPO='shorttermrentalforsale-site'
TOPICS={REPO:json.loads((ROOT/'content/field-guide-topics.json').read_text())}
W=ROOT.parent;DATE='2026-10-09'
CONFIG={
'bnb-accelerator-site':('https://www.bnbaccelerator.com','BNB Accelerator','Acquisition and owner oversight','resources/str-investor-library/index.html','resources/index.html'),
'mybnbdesign':('https://www.mybnbdesign.com','My BNB Design','Design and installation','resources/acquisition-to-design-brief/index.html','resources/index.html'),
'short-term-rental-secrets':('https://shorttermrentalsecrets.io','Short Term Rental Secrets','Launch and operations','launch-decision-log/index.html','index.html'),
 'tax-free-investors':('https://taxfreeinvestors.com','Tax Free Investors','Property records and adviser handoffs','property-project-document-handoff/index.html','index.html'),
'investinshorttermrentals-site':('https://www.investinshorttermrentals.com','Invest in Short Term Rentals','Portfolio research and capital planning',None,'resources/index.html'),
'shorttermrentalforsale-site':('https://www.shorttermrentalforsale.com','Short Term Rental for Sale','Buyer evidence and purchase handoffs',None,'resources/index.html')}
def e(s):return html.escape(s,quote=True)
def link(u,t):return f'<a href="{e(u)}">{e(t)}</a>'
CSS='''*{box-sizing:border-box}body{margin:0;background:#faf8f2;color:#182b2a;font:17px/1.75 system-ui,sans-serif}header,main,footer{max-width:1000px;margin:auto;padding:24px}header{display:flex;flex-wrap:wrap;gap:24px;justify-content:space-between;border-bottom:1px solid #d7d5ca}nav{display:flex;flex-wrap:wrap;gap:20px}main{padding-top:56px;padding-bottom:70px}h1,h2{font-family:Georgia,serif;line-height:1.15;letter-spacing:-.025em}h1{font-size:clamp(36px,5vw,58px);max-width:850px}h2{font-size:30px;margin-top:46px}p,li{max-width:800px}a{color:#765024;text-underline-offset:4px}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.13em;text-transform:uppercase}.lead{font-size:21px}.notice,fieldset,.card{padding:24px;background:#fff;border:1px solid #d7d5ca;border-radius:6px}fieldset{margin:20px 0}legend{font-weight:700}label{display:block;margin:14px 0}input[type=text],textarea{width:100%;font:inherit;padding:12px;border:1px solid #a5aaa0;border-radius:3px}input[type=checkbox]{width:19px;height:19px;vertical-align:middle;margin-right:10px}button{font:inherit;padding:12px 18px;background:#182b2a;color:white;border:0;border-radius:4px;cursor:pointer;margin:8px 12px 8px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:20px}.grid h2,.grid h3{font-size:23px;margin:0 0 12px}footer{border-top:1px solid #d7d5ca;font-size:14px}.skip{position:absolute;left:-9999px}.skip:focus{left:20px;top:12px;background:white;padding:12px}:focus-visible{outline:3px solid #ad7d38;outline-offset:4px}li{margin:10px 0}table{border-collapse:collapse;width:100%}td,th{padding:12px;border-bottom:1px solid #d7d5ca;text-align:left}.table-wrap{overflow:auto}summary{cursor:pointer;font-weight:700}.muted{font-size:14px;color:#59625d}@media(max-width:600px){header,main,footer{padding-left:20px;padding-right:20px}main{padding-top:32px}}@media print{header,nav,button,.skip,.no-print{display:none}body{background:white;color:black}main{max-width:none;padding:0}fieldset,.notice{break-inside:avoid}a{color:inherit}}'''
JS='''document.addEventListener('DOMContentLoaded',()=>{const form=document.querySelector('[data-worksheet]');if(form){const checks=[...form.querySelectorAll('input[type=checkbox]')],status=document.getElementById('worksheet-status');const update=()=>{status.textContent=checks.filter(x=>x.checked).length+' of '+checks.length+' actions checked. A checked box records your progress, not independent verification.'};form.addEventListener('change',update);document.getElementById('print-guide').addEventListener('click',()=>window.print());document.getElementById('export-worksheet').addEventListener('click',()=>{const lines=[document.querySelector('h1').textContent,'Planning worksheet — not professional approval',''];for(const field of form.querySelectorAll('input,textarea')){const label=field.closest('label')?.textContent.trim()||field.name;lines.push(field.type==='checkbox'?(field.checked?'[x] ':'[ ] ')+label:label+': '+field.value)}const blob=new Blob([lines.join('\\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=location.pathname.split('/').filter(Boolean).pop()+'-worksheet.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});update()}const search=document.getElementById('guide-search');if(search)search.addEventListener('input',()=>{const query=search.value.toLowerCase().trim();let n=0;for(const card of document.querySelectorAll('[data-guide]')){card.hidden=!card.textContent.toLowerCase().includes(query);if(!card.hidden)n++}document.getElementById('search-status').textContent=n+' matching guides'});});'''
def document(repo,path,title,description,body,kind='Article'):
 base,brand,role,template,_=CONFIG[repo];url=base+path
 schema={'@context':'https://schema.org','@type':kind,'name':title,'headline':title,'description':description,'url':url,'datePublished':DATE,'dateModified':DATE,'publisher':{'@type':'Organization','name':brand,'url':base+'/'},'mainEntityOfPage':url}
 return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{e(title)} | {e(brand)}</title><meta name="description" content="{e(description)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(description)}"><meta property="og:url" content="{url}"><meta property="og:type" content="article"><meta name="twitter:card" content="summary"><link rel="stylesheet" href="/assets/field-guides.css"><script defer src="/assets/field-guides.js"></script><script type="application/ld+json">{json.dumps(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a><header>{link(base+'/',brand)}<nav aria-label="Primary">{link('/field-guides/','Field guides')}{link('https://www.bnbaccelerator.com/resources/str-investor-library/','Investor journey')}{link('https://www.bnbaccelerator.com/apply/','Discuss acquisition support')}</nav></header><main id="main">{body}</main><footer><p>{e(brand)} · {e(role)}. Part of the related BNB resource network. Network links are navigation resources, not independent endorsements. Examples are hypothetical and do not describe client results.</p><p>These planning worksheets organize evidence and decisions. Confirm property-specific requirements and professional conclusions with the responsible adviser or provider.</p>{'<p>Tax Free Investors is a brand name, not a promise of tax-free income. This library concerns records, not tax classification or deduction eligibility.</p>' if repo=='tax-free-investors' else ''}{link('/field-guides/','Browse this site’s field guides')}</footer></body></html>'''
manifest=[]
for repo,topics in TOPICS.items():
 root=W/repo;cfg=CONFIG[repo];base,brand,role,template,placement=cfg
 assets=root/'assets';assets.mkdir(exist_ok=True);(assets/'field-guides.css').write_text(CSS);(assets/'field-guides.js').write_text(JS)
 source=root/'content';source.mkdir(exist_ok=True);(source/'field-guide-topics.json').write_text(json.dumps(topics,indent=2));records=[]
 for i,(slug,title,purpose,inputs,actions,failure,example) in enumerate(topics):
  path='/field-guides/'+slug+'/';p=root/path.strip('/')/'index.html';p.parent.mkdir(parents=True,exist_ok=True)
  inputs=inputs.split(';');actions=actions.split(';');desc=purpose.split('. ')[0]+'. Use the evidence checklist, worked example and editable planning worksheet.'
  rows=''.join(f'<tr><th scope="row">{e(x)}</th><td>Record the source, document date, reviewer and unresolved question.</td></tr>' for x in inputs)
  related=topics[(i+1)%len(topics)];network=json.loads((ROOT/'content/field-guide-network.json').read_text());next_repo=list(CONFIG)[(list(CONFIG).index(repo)+1)%len(CONFIG)];next_cfg=CONFIG[next_repo];next_topic=network[next_repo]
  body=f'<p class="eyebrow">{e(role)} · Field guide · October 9, 2026</p><h1>{e(title)}</h1><p class="lead">{e(purpose)}</p><nav aria-label="On this page">{link("#evidence","Evidence")}{link("#process","Process")}{link("#example","Example")}{link("#worksheet","Worksheet")}</nav>'
  body+='<section id="evidence"><h2>Evidence to assemble</h2><p>Gather the source records before completing the worksheet. A missing record should remain an open question. Keep the original alongside any summary so the next person can trace the decision.</p><div class="table-wrap"><table><thead><tr><th>Input</th><th>Record with it</th></tr></thead><tbody>'+rows+'</tbody></table></div></section>'
  body+='<section id="process"><h2>Work through the decision</h2><ol>'+''.join('<li>'+e(x)+'.</li>' for x in actions)+'</ol><p>For each action, name the person responsible for preparing the response and the person who approves it. Record what evidence would close the item. If new information changes cost, timing or scope, update the affected plan and identify who needs the revised version.</p><h3>Common failure to avoid</h3><p>'+e(failure)+'</p></section>'
  body+='<section id="example"><h2>Worked example</h2><p>'+e(example)+'</p><p class="muted">This is an illustrative workflow, not a client case study or a forecast. Replace the example’s facts with the records for your own project.</p></section>'
  body+='<section id="worksheet"><h2>Complete your planning worksheet</h2><p>Use the fields to connect evidence, action and approval. Your entries stay in this page and are included only when you choose to download them. They are not sent to a server and are not saved after a page reload.</p><form data-worksheet><fieldset><legend>Project context</legend><label>Property or project reference<input type="text" name="project" autocomplete="off"></label><label>Decision owner and review date<input type="text" name="owner-date" autocomplete="off"></label></fieldset><fieldset><legend>Source references</legend>'+''.join(f'<label>{e(x)}<input type="text" name="evidence-{j}" autocomplete="off"></label>' for j,x in enumerate(inputs))+'</fieldset><fieldset><legend>Action checklist</legend>'+''.join(f'<label><input type="checkbox" name="action-{j}">{e(x)}</label>' for j,x in enumerate(actions))+'</fieldset><label>Open questions, dependencies and next review<textarea name="open-questions" rows="4"></textarea></label><label>Approval and supporting evidence<textarea name="approval" rows="3"></textarea></label><p id="worksheet-status" role="status" aria-live="polite"></p><button type="button" id="export-worksheet">Download completed worksheet</button><button type="button" id="print-guide">Print guide</button></form></section>'
  body+='<section><h2>Close the handoff</h2><p>A finished worksheet should identify the result, its evidence and any remaining owner. If the result is uncertain, record the next action instead of marking the whole task complete. Keep the worksheet with the relevant source file and tell the receiving person which version applies.</p><h2>Continue the workflow</h2><ul><li>'+link('/field-guides/'+related[0]+'/',related[1])+'</li><li>'+link(next_cfg[0]+'/field-guides/'+next_topic[0]+'/',next_topic[1]+' — '+next_cfg[1])+'</li><li>'+link('/field-guides/','All '+brand+' field guides')+'</li></ul></section>'
  s=document(repo,path,title,desc,body);p.write_text(s);word_count=len(re.sub('<[^>]+>',' ',body).split());assert word_count>=400,word_count
  record={'repo':repo,'path':path,'url':base+path,'title':title,'words':word_count};records.append(record);manifest.append(record)
 hub_body=f'<p class="eyebrow">{e(role)}</p><h1>{e(brand)} field guides</h1><p class="lead">Practical evidence checks, worked examples and editable worksheets for {e(role.lower())}.</p><label>Find a guide<input id="guide-search" type="search" placeholder="Search tasks and decisions"></label><p id="search-status" role="status" aria-live="polite">{len(records)} guides</p><div class="grid">'+''.join(f'<article class="card" data-guide><h2>{link(x["path"],x["title"])}</h2><p>{e(TOPICS[repo][i][2])}</p></article>' for i,x in enumerate(records))+'</div><h2>Continue across the investor journey</h2><p>Each related site owns a different stage. Move to the next resource when your question changes.</p><ul>'+''.join('<li>'+link(c[0]+'/field-guides/',c[1]+' — '+c[2])+'</li>' for r,c in CONFIG.items() if r!=repo)+'</ul>'
 p=root/'field-guides/index.html';p.parent.mkdir(exist_ok=True);p.write_text(document(repo,'/field-guides/',brand+' field guides','Browse practical '+role.lower()+' guides with evidence checklists and editable worksheets.',hub_body,'CollectionPage'))
 manifest.append({'repo':repo,'path':'/field-guides/','url':base+'/field-guides/','title':brand+' field guides','words':len(re.sub('<[^>]+>',' ',hub_body).split())})

print(json.dumps({'site':REPO,'guides':len(TOPICS[REPO]),'regenerated':True}))
